// src/models/school.ts

import { BaseEntity } from '../types';

export interface School extends BaseEntity {
  name: string;
  subdomain: string;
  admin_email: string;
  package: string; // e.g., 'Basic', 'Premium'
  status: string; // e.g., 'Active', 'Pending', 'Suspended'
  student_limit: number;
  teacher_limit: number;
  admin_limit: number;
  branding_settings: {
    appName?: string;
    appIconUrl?: string;
    primaryColor?: string;
    secondaryColor?: string;
    [key: string]: any; // Allow other properties
  };
  module_settings: {
    messaging?: boolean;
    portfolio?: boolean;
    [key: string]: any; // Allow other properties
  };
  timezone: string;
  currency_code: string;
  academic_year_start?: string; // ISO date string
  academic_year_end?: string;   // ISO date string
}

// For creating a new school (id and timestamps are generated by DB)
export type CreateSchoolPayload = Omit<School, 'id' | 'created_at' | 'updated_at'>;
// For updating a school (id is in params, timestamps managed by DB)
export type UpdateSchoolPayload = Partial<Omit<School, 'id' | 'created_at' | 'updated_at'>>;